[dev]
  command = "sleep 999999999"
  framework = "#custom"
  functions = ".output/server"
  port = 8888
  targetPort = 3000

[build]
  command = "yarn build"
  publish = "dist"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
